export const fullInvalidBoard: any[][] = [
	[
		{ isFixed: true, value: 9 },
		{ isFixed: true, value: 1 },
		{ isFixed: true, value: 4 },
		{ isFixed: true, value: 5 },
		{ isFixed: true, value: 7 },
		{ isFixed: true, value: 3 },
		{ isFixed: true, value: 8 },
		{ isFixed: true, value: 2 },
		{ isFixed: true, value: 6 },
	],
	[
		{ isFixed: true, value: 5 },
		{ isFixed: true, value: 3 },
		{ isFixed: true, value: 2 },
		{ isFixed: true, value: 4 },
		{ isFixed: true, value: 8 },
		{ isFixed: true, value: 6 },
		{ isFixed: true, value: 1 },
		{ isFixed: true, value: 7 },
		{ isFixed: true, value: 9 },
	],
	[
		{ isFixed: true, value: 9 },
		{ isFixed: true, value: 1 },
		{ isFixed: true, value: 3 },
		{ isFixed: true, value: 4 },
		{ isFixed: true, value: 2 },
		{ isFixed: true, value: 5 },
		{ isFixed: true, value: 8 },
		{ isFixed: true, value: 6 },
		{ isFixed: true, value: 7 },
	],
	[
		{ isFixed: true, value: 7 },
		{ isFixed: true, value: 1 },
		{ isFixed: true, value: 8 },
		{ isFixed: true, value: 2 },
		{ isFixed: true, value: 9 },
		{ isFixed: true, value: 3 },
		{ isFixed: true, value: 4 },
		{ isFixed: true, value: 5 },
		{ isFixed: true, value: 6 },
	],
	[
		{ isFixed: true, value: 9 },
		{ isFixed: true, value: 7 },
		{ isFixed: true, value: 1 },
		{ isFixed: true, value: 3 },
		{ isFixed: true, value: 2 },
		{ isFixed: true, value: 6 },
		{ isFixed: true, value: 5 },
		{ isFixed: true, value: 8 },
		{ isFixed: true, value: 4 },
	],
	[
		{ isFixed: true, value: 5 },
		{ isFixed: true, value: 3 },
		{ isFixed: true, value: 1 },
		{ isFixed: true, value: 7 },
		{ isFixed: true, value: 4 },
		{ isFixed: true, value: 2 },
		{ isFixed: true, value: 9 },
		{ isFixed: true, value: 8 },
		{ isFixed: true, value: 6 },
	],
	[
		{ isFixed: true, value: 1 },
		{ isFixed: true, value: 8 },
		{ isFixed: true, value: 6 },
		{ isFixed: true, value: 5 },
		{ isFixed: true, value: 3 },
		{ isFixed: true, value: 9 },
		{ isFixed: true, value: 2 },
		{ isFixed: true, value: 4 },
		{ isFixed: true, value: 7 },
	],
	[
		{ isFixed: true, value: 7 },
		{ isFixed: true, value: 1 },
		{ isFixed: true, value: 5 },
		{ isFixed: true, value: 9 },
		{ isFixed: true, value: 2 },
		{ isFixed: true, value: 4 },
		{ isFixed: true, value: 6 },
		{ isFixed: true, value: 8 },
		{ isFixed: true, value: 3 },
	],
	[
		{ isFixed: true, value: 1 },
		{ isFixed: true, value: 3 },
		{ isFixed: true, value: 7 },
		{ isFixed: true, value: 5 },
		{ isFixed: true, value: 8 },
		{ isFixed: true, value: 4 },
		{ isFixed: true, value: 2 },
		{ isFixed: true, value: 9 },
		{ isFixed: true, value: 6 },
	],
];
